[profile.default]
via_ir = true
optimizer = true
src = "contracts"
out = "artifacts"
libs = ["lib", "dependencies"]

# Ignore compiler warnings that should be intentionally-skipped
ignored_warnings_from = ["contracts/utils/external/MockERC20.sol","contracts/utils/external/MockUniswapV2Router.sol","test/Token.t.sol","test/ImagineFactory.t.sol"]


[dependencies]
"@openzeppelin-contracts" = "5.1.0"
"@uniswap-v2-core" = "1.0.1"
"@uniswap-v2-periphery" = "1.1.0-beta.0"


[rpc_endpoints]
rpc = "${RPC}"
localhost = "http://localhost:8545"


