[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.1.0"
"@uniswap-v2-core" = "1.0.1"
"@uniswap-v2-periphery" = "1.1.0-beta.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


# forge script script/DeployImagineFactory.s.sol:DeployImagineFactory --rpc-url <RPC_URL> --broadcast --etherscan-api-key <ETHERSCAN_API_KEY> --verify
