name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Icov for coverage
        run: |
          sudo apt install lcov

      - name: Forge install soldeer
        run: |
          forge soldeer install

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --via-ir --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test --via-ir -vvvv
        id: test

      - name: Run coverage
        run: |
          forge coverage --ir-minimum --report lcov
          genhtml lcov.info --branch-coverage --output-dir coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      # - name: Upload coverage to Coveralls
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      #   run: npx coveralls <  ./lcov.info
